add:
  soundeffect: "ENTITY_PLAYER_LEVELUP"
  globalsound: false
remove:
  soundeffect: "ENTITY_CAT_HURT"
  globalsound: false
equip:
  soundeffect: "ITEM_ARMOR_EQUIP_CHAIN"
  globalsound: true
dequip:
  soundeffect: "ITEM_ARMOR_EQUIP_CHAIN"
  globalsound: true

permissions:
  hat_equip: "hats.equip"
  hat_add: "hats.add"
  hat_remove: "hats.remove"
  reload_config: "hats.reloadconfig"
